# Create date : 2019-04-15 / by Woo Hyung Choi / whchoi@cisco.com, whchoi98@gmail.com
# ansible for the NXOS fact check. - HTTP API based
# Note
# Test env : Tested against NXOS 9.2(2), Ansible 2.7
# Must be :  feature ssh,nxapi must be enable for ansible connection by HTTPAPI and feature ssh,nxapi,privilege must be enable for ansible connection by network_cli.

- name: nxos_fact.yml 
  hosts: all 

  tasks:
    - name: nxos_facts gather config
      nxos_facts:
        gather_subset:
          - config
      register: output
    - debug: var=output



#  Reference Site : https://docs.ansible.com/ansible/latest/modules/nxos_facts_module.html#examples