# Create date : 2019-04-15 / by Woo Hyung Choi / whchoi@cisco.com, whchoi98@gmail.com
# ansible for the NXOS interface factory config.
# Note
# Test env : Tested against NXOS 9.2(2), Ansible 2.7
# Must be :  feature ssh,nxapi must be enable for ansible connection by HTTPAPI and feature ssh,nxapi,privilege must be enable for ansible connection by network_cli.

- name: nxos_interface_factory.yml 
  hosts: all 
  connection: httpapi

  tasks:
    - name: interface setting for the L3 Interface 
      nxos_config:
        lines: 
          - default interface ethernet 1/21 -25

    - name: Saving running conf for changed targets
      nxos_command:
        commands: copy running-config startup-config
      changed_when: True


