# group vars files
# directory - ./group_vars

nxos_provider:
  transport: nxapi
  hosts: "{{ inventory_hostname }}"
  ssh_keyfile: "{{ ssh_private_key }}"
  username: "{{ username }}"
  password: "{{ password }}"
   
nxos_ssh:
  transport: network_cli
  host: "{{ inventory_hostname }}"
  ssh_keyfile: "{{ ssh_private_key }}"
  username: "{{ username }}"
  password: "{{ password }}"
    
nxos_nxapi:
  transport: nxapi
  hosts: "{{ inventory_hostname }}"
  ssh_keyfile: "{{ ssh_private_key }}"
  username: "{{ username }}"
  password: "{{ password }}"
  use_ssl: yes
  validate_certs: no
  port: 443
      