# Create date : 2019-04-15 / by Woo Hyung Choi / whchoi@cisco.com, whchoi98@gmail.com
# ansible for the NXOS fact check. - nxapi , ssh

- name: nxos_fact.yml 
  hosts: all 
  connection: local

  vars:
    nxos_provider:
      transport: nxapi      
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      ssh_keyfile: "{{ ssh_private_key }}"
      use_ssl: yes
      validate_certs: no
   
    nxos_ssh:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      ssh_keyfile: "{{ ssh_private_key }}"
    
    nxos_nxapi:
      transport: nxapi      
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      ssh_keyfile: "{{ ssh_private_key }}"
      use_ssl: yes
      validate_certs: no

  tasks:
    - name: nxos_provider
      nxos_facts:
        provider: "{{ nxos_provider }}"

    - name: nxos_facts SSH connecttion test
      nxos_facts:
        provider: "{{ nxos_ssh }}"

    - name: nxos_facts nxapi connection test
      nxos_facts:
        provider: "{{ nxos_nxapi }}"

    - name: nxos_facts gather config
      nxos_facts:
        provider: "{{ nxos_nxapi }}"
        gather_subset:
          - config

#  Reference Site : https://docs.ansible.com/ansible/latest/modules/nxos_facts_module.html#examples