all:
    
    hosts:
    
    vars:
      group_var:
    
    children:
      spine:
        hosts:
          NXOS-SPINE-1001:
            ansible_host: 10.72.86.143
          NXOS-SPINE-1002:
            ansible_host: 10.72.86.144
      leaf:
        hosts:
          NXOS-LEAF-1003:
            ansible_host: 10.72.86.145
          NXOS-LEAF-1004:
            ansible_host: 10.72.86.146
          NXOS-LEAF-1005:
            ansible_host: 10.72.86.147
          NXOS-LEAF-1006:
            ansible_host: 10.72.86.148
